### PR TITLE
some audio functions for openreception

### PR DESCRIPTION
**Pull request by lpl1977**
Hello

Here are a couple of files that play and stop sounds and may be of use.

Lee

### CODE REVIEW

**Comment by jonaskn** [comment]
Hi Lee

the two files look good and reasonable.
I have two small requests. No need to close the pull request. You can just commit the changes and the pull request will update. 
1. The help text still has pds.behavior... in it. Please change to the actual location (pds.audio...)
2. The standard way to check for missing parameters (e.g. 'repeats') is to use nargin in.
   `if nargin <3`
   `repeats = 1;`
   `end`

`if isinf(repeats)`
`repeats=0;`
`end`

jonas

**Comment by lpl1977** [comment]
OK done

**Comment by jonaskn** [comment]
ok,  there are now a number of unrelated commits in here that should not be included in the pull request.  I will move this to a new pdsAudioStartStop branch and see what to do from there. Also the parameter p.trial.sound.useForReward if not defined in the defaults yet, correct?

**Comment by lpl1977** [comment]
That's right I created that flag.

Sorry about the multiple commits half of them are garbage from me figuring out what to do.

Sent from my iPhone

On Sep 15, 2016, at 6:02 PM, jonaskn <notifications@github.com<mailto:notifications@github.com>> wrote:

ok, there are now a number of unrelated commits in here that should not be included in the pull request. I will move this to a new pdsAudioStartStop branch and see what to do from there. Also the parameter p.trial.sound.useForReward if not defined in the defaults yet, correct?

**Comment by jonaskn** [comment]
I just merged from the pdsAudioStartStop branch to openreception.

**Pull request merged**
