### PR TITLE
correcting case sensitivity for isfield function calls

### PR DESCRIPTION
**Pull request by wzinke**
On linux with recent matlab version 16a it seems that isField is not recognized as function. Also, there is an instance where isField is referring to a bolean variable that could result in an error.

### CODE REVIEW

**Comment by jonaskn** [comment]
Hi @wzinke ,

this is most likely not a bug.

isField is a method from the params class (p.defaultParameters and p.trial (outside of trials)). The reported behavior sounds like p.trial was a struct when isField was called. Can you recall what the circumstances were that led to the first error with this? 
Also, the changes you made would not work, because isfield does not support querying substructs (at least in 2015b), so that e.g. isfield(p.trial, 'pldaps.dirs.wavfiles') would always return false (correct would be isfield(p.trial, 'pldaps') && isfield(p.trial.pldaps, 'dirs') && isfield(p.trial.pldaps.dirs, 'wavfiles').

The issue could be solved by replacing isField(p.trial,...) with isField(p.defaultParameters,...), but I'd first like to track down under what circumstances these functions get called with p.trial as a struct.
We could also create a generic function isField that can handle structs and params.  

I agree that the use of isField as a variable in params.subsasgn can be confusing, though it should not cause an error. But we should change that either way.

thanks for you contribution
jonas

**Comment by wzinke** [comment]
Hi,

Thanks for the quick reaction. I am in the process to get PLDAPS working 
for Anita Disneys Lab, and at the moment I follow the description in the 
Github readme file, initializing the small screen by loading the 
settings and then executing p.run. I ran into the error message that 
'isField' is an undefined function (error in openScreen line 120). So I 
checked the spelling and found several occurrences of isfield where it 
is used as the function but with capital F. This is not recognized by 
Matlab 2016a on linux Mint. Accordingly, the variable isField should 
work, but I think it is prone for trouble and rather would rename it to 
be clearly distinct from the function.

wolf

**Comment by jonaskn** [comment]
Hi,

I don't have Matlab 2016 on any machine right now.
Can you:
1. Check if p.defaultParameters and p.trial are of class params before you p.run (unchanged pldaps)
2. set 'dbstop if caught error' and check the same when you get the error in openScreen
3. if it is a params class, check if pa=pldaps.defaultParameters; isField(pa,'test') works?

jonas

**Comment by wzinke** [comment]
Hi,

See below the commands and output. When I first execute p.run it seems to
start fine with the problem that it tries to create a temp file in a
directory without write permissions - in p.trial.session.dir '/DATA' is
specified and does not exist on this machine. I exit debug mode and execute
p.run again and it throws the isField error. I am sorry I overlooked that
the error occurred after another error stopped everything.

wolf

> > load settingsStruct;>> isfield(p,'test')

ans =

```
 0
```

> > p=pldaps(@plain,'test',settingsStruct)
> > p =

  pldaps with properties:

```
defaultParameters: [1x1 params]
       conditions: {}
            trial: [1x1 params]
             data: {}
  functionHandles: []
```

> > p.defaultParameters

ans =

  params with properties:

```
     structs: {[1x1 struct]  []  [1x1 struct]  [1x1 struct]}
 structNames: {1x4 cell}
activeLevels: [1 1 1 1]
    topLevel: 4
  flatStruct: [1x131 struct]
      locked: []
 MethodsList: {1x12 cell}
       Snew1: [1x2 struct]

with public methods:
```

view
setLevels
getAllLevels
mergeToSingleStruct
getDifferenceFromStruct
addLevels
addStructs
addNewStruct
getAllStructs
setLock
getParameter
fieldnames

```
with fieldnames:
```

behavior
datapixx
display
eyelink
git
mouse
newEraSyringePump
pldaps
plexon
session
sound

isField(p,'test')
Undefined function 'isField' for input arguments of type 'pldaps'.

> > isfield(p,'test')

ans =

```
 0
```

**Comment by jonaskn** [comment]
ok, that explains it. We could mark a pldaps object as 'used' to prevent run from running a second time to prevent this confusion in the future.

What happens when you create that directory or alternatively set
`settingsStruct.pldaps.dirs.data='~/PLDAPSData'`
or some other directory you created (before creating the pldaps object)?

also, the isField check would have to be 
`isField(p.trial, 'test')`
or
`pa=p.trial; isField(pa,'test')`

jonas

**Comment by wzinke** [comment]
Hi,

I followed your suggestion and changed the directory to the current working
directory. The when executing p.run, the p.trial.session.dir enty is still
'/Data' and saveTempFile throws an error because of permission issues.

> > load settingsStruct;
> > p=pldaps(@plain,'test',settingsStruct)
> > settingsStruct.pldaps.dirs.data=pwd
> > settingsStruct.pldaps.dirs.data

ans =

/home/rig2-user/Data/PLDAPS/wz_getstarted

I created a directory link named '/Data' and verified in the shell that I
have writing permissions. I get a message ("Cannot create
'test20160922plain15120.PDS' because '/Data/TEMP' does not exist."), but
the screen shows up with y and x scales and additional marks. I
created '/Data/TEMP' and the screen showed up without message. However,
when stopping the trial by entering 'p' no temp file was created (might be
what is expected anyway for the test set up).

I tried to find the file where p.trial.session.dir is assigned to be
'/Data' but did not see it yet (search for text srtring  'in all *.m
files). Where is this entry set?

wolf

**Comment by jonaskn** [comment]
Hi,

you need to change the parameter before passing it to pldaps

> load settingsStruct; 
> settingsStruct.pldaps.dirs.data=pwd 
> p(@plain,'test',settingsStruct) 

Saving of temp files is done in pldaps.saveTempFiles

jonas

**Comment by wzinke** [comment]
OK, sorry it was my bad. The right order made sure that the changed
directory is asigned. However, it still expects that the TEMP directory was
created prior start. It might be good either to not use a TEMP
subdirectory, or in the saveTempFile try to create it if it is not existing
(and issue a message where to find temp files if needed).

Thanks for the quick help,
wolf

**Comment by jonaskn** [comment]
ok. I'm closing this pull request.

btw, saveTempFile does create the TMP directory if it does not exist (in a catch statement).

**Pull request closed without merging**
